export type BackgroundDto =
  | 'forest.png'
  | 'loadingBg.png'
  | 'homeLoading.png'
  | 'greenForest.png'
  | 'snow.png'
  | 'desert.png'
  | 'fire.png'
  | 'zeldaSkyloft.png'
  | 'zeldaForest.png'
  | 'zeldaVolcano.png'
  | 'zeldaDesert.png'
  | 'zeldaForest2.png'
  | 'zeldaFinal1.png'
  | 'zeldaFinal2.png';
